services:
  loadtestpostgresrediscache:
    image: ${DOCKER_REGISTRY-}loadtestpostgresrediscache
    build:
      context: .
      dockerfile: LoadTestPostgresRedisCache/Dockerfile
    depends_on:       
      - postgresdb
    ports:
      - "5003:8080"

  postgresdb:
    image: postgres:latest
    container_name: postgrescontainer
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "1234:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  newsletter.api:
    image: ${DOCKER_REGISTRY-}newsletterapi
    build:
      context: .
      dockerfile: NewsLetter.API/Dockerfile
    ports:
      - "5001:8080"

  newsletter.reporting.api:
    image: ${DOCKER_REGISTRY-}newsletterreportingapi
    build:
      context: .
      dockerfile: NewsLetter.Reporting.API/Dockerfile
    ports:
       - "5002:8080"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol (for apps)
      - "15672:15672"  # HTTP UI (management console)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  pgdata:
  rabbitmq_data:


